from typing import Union
from pydantic import BaseModel, Field


class SymptomScheme(BaseModel):
    itching : float
    skin_rash : float
    nodal_skin_eruptions : float
    continuous_sneezing : float
    shivering : float
    chills : float
    joint_pain : float
    stomach_pain : float
    acidity : float
    ulcers_on_tongue : float
    muscle_wasting : float
    vomiting : float
    burning_micturition : float
    spotting_ : float
    fatigue : float
    weight_gain : float
    anxiety : float
    mood_swings : float
    weight_loss : float
    restlessness : float
    lethargy : float
    irregular_sugar_level : float
    cough : float
    high_fever : float
    sunken_eyes : float
    breathlessness : float
    sweating : float
    indigestion : float
    headache : float
    yellowish_skin : float
    dark_urine : float
    nausea : float
    loss_of_appetite : float
    pain_behind_the_eyes : float
    back_pain : float
    constipation : float
    abdominal_pain : float
    diarrhoea : float
    mild_fever : float
    yellow_urine : float
    yellowing_of_eyes : float
    acute_liver_failure : float
    swelling_of_stomach : float
    swelled_lymph_nodes : float
    malaise : float
    blurred_and_distorted_vision : float
    phlegm : float
    throat_irritation : float
    chest_pain : float
    weakness_in_limbs : float
    fast_heart_rate : float
    pain_during_bowel_movements : float
    neck_pain : float
    dizziness : float
    cramps : float
    obesity : float
    knee_pain : float
    muscle_weakness : float
    stiff_neck : float
    swelling_joints : float
    movement_stiffness : float
    spinning_movements : float
    loss_of_balance : float
    weakness_of_one_body_side : float
    bladder_discomfort : float
    passage_of_gases : float
    toxic_look_ : float
    depression : float
    irritability : float
    muscle_pain : float
    red_spots_over_body : float
    family_history : float
    mucoid_sputum : float
    rusty_sputum : float
    lack_of_concentration : float
    visual_disturbances : float
    blood_in_sputum : float
    pus_filled_pimples : float
    skin_peeling : float
    blister : float